### ISSUE TITLE
Does this library supports fuzzy search?

### ISSUE THREAD

**Issue by rmariuzzo** [swisnl/laravel-fulltext#13]
## Detailed description

Questions: Does this library supports fuzzy search?

## Context

I would like to implement fuzzy search.

## Possible implementation

Levenshtein?

## Your environment

* Laravel 5.1

**Comment by bbrala** [comment]
This library only provides an automated way to make an MySQL fulltext index. There is no fuzzy search support in FULLTEXT.

**Comment by rmariuzzo** [comment]
Thank you.
