### ISSUE TITLE
Working with relationship in model

### ISSUE THREAD

**Issue by yblancof2** [swisnl/laravel-fulltext#4]
Good morning, I need to know how to index relationships in depth. I explain below
User has many books and books have authors. I need to know how to know what the authors read the users.
This would be the relationship in depth.
user.book.author.name
Also want to know what the difference between $ indexTitleColumns and $ indexContentColumns is.
Regards

**Comment by bbrala** [comment]
From what i see in the code i don't think nested relations are possible at this point. You might be able to do it with a `getBookAuthorsAttribute` function which then fetched the deeper relation on the model. This can then be indexed as a normal attribute of the model.

The difference in the two columns is mostly regarding [to weight](https://github.com/swisnl/laravel-fulltext#weighttitle-weightcontent), so you van give certain fields a higher weight in the search than the raw content.
